#!/usr/bin/env bash

# This script facilitates the secure transfer of a file from Holberton's client to another server using SCP (Secure Copy Protocol).
# It accepts four arguments:
# 1. The path to the file to be transferred.
# 2. The IP address of the destination server.
# 3. The username for authentication during the SCP transfer.
# 4. The path to the SSH private key used by SCP for authentication.
if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi

