#!/usr/bin/env bash

# Ping an IP Address 5 Times
# This script pings a specified IP address five times to check its reachability and response time.
# Usage: 5-is_the_host_on_the_network {IP_ADDRESS}
# Replace {IP_ADDRESS} with the target IP address you want to ping.
# Useful for network diagnostics and checking host availability.

if [ $# -eq 0 ]
then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
  ping -c 5 "$1"
fi
