#!/usr/bin/env bash
# PID-based process with signal handling

# Creates a PID file /var/run/myscript.pid containing the script PID.
# Displays "To infinity and beyond" indefinitely.
# Responds to SIGTERM with "I hate the kill command."
# Responds to SIGINT with "Y U no love me?!"
# Deletes the PID file /var/run/myscript.pid and terminates on SIGQUIT or SIGTERM.

terminator() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUIT
done
